# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  employee_insert(
    data: {id: "11111111222233334444555555555555", userId: "11111111222233334444555555555555", address: "", fullName: "", hiringDate: "2025-04-11", nationalId: "", phone: "", specialty: ""}
  )
}