
# This is a file for you to write an un-named query.
# Only one un-named query is allowed per file.
query {
  programmers{
    user {
      name
      email
      password
      role
    }
    nationalId
    phone
    address
    hiringDate
  }
}